services:
  backend:
    image: backend-app
    build:
      context: ../../../../../../tmp/material-applications/example-backend
      dockerfile: Dockerfile
    container_name: example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000

  frontend:
    image: frontend-app
    build:
      context: ../../../../../../tmp/material-applications/example-frontend
      dockerfile: Dockerfile
    container_name: example-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
