services:
  backend:
    image: backend-app
    build:
      context: ../../../../../../tmp/material-applications/example-backend
      dockerfile: Dockerfile
    container_name: example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - db
    restart: unless-stopped

  frontend:
    image: frontend-app
    build:
      context: ../../../../../../tmp/material-applications/example-frontend
      dockerfile: Dockerfile
    container_name: example-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    container_name: db_postgres
    volumes:
      - ./database:/var/lib/postgresql/data
